# Generated by Django 4.1.3 on 2022-11-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_persona_create_at_alter_persona_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
