# Generated by Django 4.1.3 on 2022-11-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_persona_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
